// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mist.Data;

#nullable disable

namespace Mist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516110557_AddUserProfileFields")]
    partial class AddUserProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mist.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.Generation", b =>
                {
                    b.Property<int>("GenerationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("generation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenerationId"));

                    b.Property<DateTime?>("GenerationCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generation_created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GenerationUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("generation_user_id");

                    b.Property<int?>("GenerationVideoId")
                        .HasColumnType("int")
                        .HasColumnName("generation_video_id");

                    b.HasKey("GenerationId")
                        .HasName("PK__generati__F887D65A3DD55360");

                    b.HasIndex("GenerationUserId");

                    b.HasIndex("GenerationVideoId");

                    b.ToTable("generation", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatform", b =>
                {
                    b.Property<int>("GenerationPlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenerationPlatformId"));

                    b.Property<string>("GenerationPlatformCustomPrompt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("generation_platform_custom_prompt");

                    b.Property<string>("GenerationPlatformGeneratedHashtags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("generation_platform_generated_hashtags");

                    b.Property<string>("GenerationPlatformGeneratedText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("generation_platform_generated_text");

                    b.Property<int?>("GenerationPlatformGenerationId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_generation_id");

                    b.Property<int?>("GenerationPlatformPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_platform_id");

                    b.HasKey("GenerationPlatformId")
                        .HasName("PK__generati__C3847D27B684AF25");

                    b.HasIndex("GenerationPlatformPlatformId");

                    b.HasIndex(new[] { "GenerationPlatformGenerationId", "GenerationPlatformPlatformId" }, "UQ__generati__5F121C0B95AADF25")
                        .IsUnique()
                        .HasFilter("[generation_platform_generation_id] IS NOT NULL AND [generation_platform_platform_id] IS NOT NULL");

                    b.ToTable("generation_platform", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatformMusicTrack", b =>
                {
                    b.Property<int>("GenerationPlatformMusicTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_music_track_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenerationPlatformMusicTrackId"));

                    b.Property<int?>("GenerationPlatformMusicTrackGenerationPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_music_track_generation_platform_id");

                    b.Property<int?>("GenerationPlatformMusicTrackMusicId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_music_track_music_id");

                    b.HasKey("GenerationPlatformMusicTrackId")
                        .HasName("PK__generati__14848B198C25FA94");

                    b.HasIndex("GenerationPlatformMusicTrackMusicId");

                    b.HasIndex(new[] { "GenerationPlatformMusicTrackGenerationPlatformId" }, "UQ__generati__39544437D683B3B5")
                        .IsUnique()
                        .HasFilter("[generation_platform_music_track_generation_platform_id] IS NOT NULL");

                    b.ToTable("generation_platform_music_track", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatformPhoto", b =>
                {
                    b.Property<int>("GenerationPlatformPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_photo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenerationPlatformPhotoId"));

                    b.Property<int?>("GenerationPlatformPhotoGenerationPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_photo_generation_platform_id");

                    b.Property<int?>("GenerationPlatformPhotoPhotoId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_photo_photo_id");

                    b.Property<int?>("GenerationPlatformPhotoPlatformPhotoFormatId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_photo_platform_photo_format_id");

                    b.HasKey("GenerationPlatformPhotoId")
                        .HasName("PK__generati__26EB45BF729145AE");

                    b.HasIndex("GenerationPlatformPhotoGenerationPlatformId");

                    b.HasIndex("GenerationPlatformPhotoPhotoId");

                    b.HasIndex("GenerationPlatformPhotoPlatformPhotoFormatId");

                    b.ToTable("generation_platform_photo", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatformTone", b =>
                {
                    b.Property<int>("GenerationPlatformToneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_tone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenerationPlatformToneId"));

                    b.Property<int?>("GenerationPlatformToneGenerationPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_tone_generation_platform_id");

                    b.Property<int?>("GenerationPlatformToneToneId")
                        .HasColumnType("int")
                        .HasColumnName("generation_platform_tone_tone_id");

                    b.HasKey("GenerationPlatformToneId")
                        .HasName("PK__generati__E7F79C567C9A0627");

                    b.HasIndex("GenerationPlatformToneToneId");

                    b.HasIndex(new[] { "GenerationPlatformToneGenerationPlatformId" }, "UQ__generati__FEFCA7CCE2115AFF")
                        .IsUnique()
                        .HasFilter("[generation_platform_tone_generation_platform_id] IS NOT NULL");

                    b.ToTable("generation_platform_tone", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.Music", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("music_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusicId"));

                    b.Property<int?>("MusicAuthorId")
                        .HasColumnType("int")
                        .HasColumnName("music_author_id");

                    b.Property<int?>("MusicDuration")
                        .HasColumnType("int")
                        .HasColumnName("music_duration");

                    b.Property<string>("MusicGenre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("music_genre");

                    b.Property<int?>("MusicPixabayId")
                        .HasColumnType("int")
                        .HasColumnName("music_pixabay_id");

                    b.Property<string>("MusicPreviewUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("music_preview_url");

                    b.Property<string>("MusicTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("music_title");

                    b.HasKey("MusicId")
                        .HasName("PK__music__B1C42D0BF4E86D9D");

                    b.HasIndex("MusicAuthorId");

                    b.HasIndex(new[] { "MusicPixabayId" }, "UQ__music__EB599E8E7476271E")
                        .IsUnique()
                        .HasFilter("[music_pixabay_id] IS NOT NULL");

                    b.ToTable("music", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.MusicAuthor", b =>
                {
                    b.Property<int>("MusicAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("music_author_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusicAuthorId"));

                    b.Property<string>("MusicAuthorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("music_author_name");

                    b.Property<int?>("MusicAuthorPixabayId")
                        .HasColumnType("int")
                        .HasColumnName("music_author_pixabay_id");

                    b.HasKey("MusicAuthorId")
                        .HasName("PK__music_au__5D3599146C10ADF4");

                    b.HasIndex(new[] { "MusicAuthorPixabayId" }, "UQ__music_au__68C637690D6937C7")
                        .IsUnique()
                        .HasFilter("[music_author_pixabay_id] IS NOT NULL");

                    b.ToTable("music_author", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("PhotoTypeId")
                        .HasColumnType("int")
                        .HasColumnName("photo_type_id");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("photo_url");

                    b.HasKey("PhotoId")
                        .HasName("PK__photo__CB48C83D0242559A");

                    b.HasIndex("PhotoTypeId");

                    b.HasIndex(new[] { "PhotoUrl" }, "UQ__photo__1464808BCF073DD7")
                        .IsUnique()
                        .HasFilter("[photo_url] IS NOT NULL");

                    b.ToTable("photo", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.PhotoFormatType", b =>
                {
                    b.Property<int>("PhotoFormatTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photo_format_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoFormatTypeId"));

                    b.Property<string>("PhotoFormatTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("photo_format_type_name");

                    b.HasKey("PhotoFormatTypeId")
                        .HasName("PK__photo_fo__B76EA87C491AB0F2");

                    b.ToTable("photo_format_type", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.PhotoType", b =>
                {
                    b.Property<int>("PhotoTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photo_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoTypeId"));

                    b.Property<string>("PhotoTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("photo_type_name");

                    b.HasKey("PhotoTypeId")
                        .HasName("PK__photo_ty__717B633E4C201C64");

                    b.ToTable("photo_type", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("PlatformDescription")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("platform_description");

                    b.Property<int?>("PlatformMaxCharacters")
                        .HasColumnType("int")
                        .HasColumnName("platform_max_characters");

                    b.Property<string>("PlatformName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("platform_name");

                    b.Property<string>("PlatformPostingTimeSuggestion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("platform_posting_time_suggestion");

                    b.HasKey("PlatformId")
                        .HasName("PK__platform__5F8F663CA60B7156");

                    b.ToTable("platform", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.PlatformPhotoFormat", b =>
                {
                    b.Property<int>("PlatformPhotoFormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("platform_photo_format_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformPhotoFormatId"));

                    b.Property<int?>("PlatformPhotoFormatHeight")
                        .HasColumnType("int")
                        .HasColumnName("platform_photo_format_height");

                    b.Property<int?>("PlatformPhotoFormatPlatformId")
                        .HasColumnType("int")
                        .HasColumnName("platform_photo_format_platform_id");

                    b.Property<int?>("PlatformPhotoFormatTypeId")
                        .HasColumnType("int")
                        .HasColumnName("platform_photo_format_type_id");

                    b.Property<int?>("PlatformPhotoFormatWidth")
                        .HasColumnType("int")
                        .HasColumnName("platform_photo_format_width");

                    b.HasKey("PlatformPhotoFormatId")
                        .HasName("PK__platform__BEE53985BB33B93A");

                    b.HasIndex("PlatformPhotoFormatPlatformId");

                    b.HasIndex("PlatformPhotoFormatTypeId");

                    b.ToTable("platform_photo_format", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.Tone", b =>
                {
                    b.Property<int>("ToneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToneId"));

                    b.Property<string>("ToneDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tone_description");

                    b.Property<string>("ToneName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tone_name");

                    b.HasKey("ToneId")
                        .HasName("PK__tone__B94ECD213A176693");

                    b.ToTable("tone", (string)null);
                });

            modelBuilder.Entity("Mist.Models.Generated.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("VideoChannelName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("video_channel_name");

                    b.Property<string>("VideoDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_description");

                    b.Property<string>("VideoTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("video_title");

                    b.Property<string>("VideoYoutubeId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("video_youtube_id");

                    b.HasKey("VideoId")
                        .HasName("PK__video__E8F11E1099286C88");

                    b.HasIndex(new[] { "VideoYoutubeId" }, "UQ__video__2A5DFD1820BEA56F")
                        .IsUnique()
                        .HasFilter("[video_youtube_id] IS NOT NULL");

                    b.ToTable("video", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mist.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mist.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mist.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mist.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mist.Models.Generated.Generation", b =>
                {
                    b.HasOne("Mist.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GenerationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mist.Models.Generated.Video", "GenerationVideo")
                        .WithMany("Generations")
                        .HasForeignKey("GenerationVideoId")
                        .HasConstraintName("FK__generatio__gener__5070F446");

                    b.Navigation("GenerationVideo");
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatform", b =>
                {
                    b.HasOne("Mist.Models.Generated.Generation", "GenerationPlatformGeneration")
                        .WithMany("GenerationPlatforms")
                        .HasForeignKey("GenerationPlatformGenerationId")
                        .HasConstraintName("FK__generatio__gener__5535A963");

                    b.HasOne("Mist.Models.Generated.Platform", "GenerationPlatformPlatform")
                        .WithMany("GenerationPlatforms")
                        .HasForeignKey("GenerationPlatformPlatformId")
                        .HasConstraintName("FK__generatio__gener__5629CD9C");

                    b.Navigation("GenerationPlatformGeneration");

                    b.Navigation("GenerationPlatformPlatform");
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatformMusicTrack", b =>
                {
                    b.HasOne("Mist.Models.Generated.GenerationPlatform", "GenerationPlatformMusicTrackGenerationPlatform")
                        .WithOne("GenerationPlatformMusicTrack")
                        .HasForeignKey("Mist.Models.Generated.GenerationPlatformMusicTrack", "GenerationPlatformMusicTrackGenerationPlatformId")
                        .HasConstraintName("FK__generatio__gener__5EBF139D");

                    b.HasOne("Mist.Models.Generated.Music", "GenerationPlatformMusicTrackMusic")
                        .WithMany("GenerationPlatformMusicTracks")
                        .HasForeignKey("GenerationPlatformMusicTrackMusicId")
                        .HasConstraintName("FK__generatio__gener__5FB337D6");

                    b.Navigation("GenerationPlatformMusicTrackGenerationPlatform");

                    b.Navigation("GenerationPlatformMusicTrackMusic");
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatformPhoto", b =>
                {
                    b.HasOne("Mist.Models.Generated.GenerationPlatform", "GenerationPlatformPhotoGenerationPlatform")
                        .WithMany("GenerationPlatformPhotos")
                        .HasForeignKey("GenerationPlatformPhotoGenerationPlatformId")
                        .HasConstraintName("FK__generatio__gener__628FA481");

                    b.HasOne("Mist.Models.Generated.Photo", "GenerationPlatformPhotoPhoto")
                        .WithMany("GenerationPlatformPhotos")
                        .HasForeignKey("GenerationPlatformPhotoPhotoId")
                        .HasConstraintName("FK__generatio__gener__6383C8BA");

                    b.HasOne("Mist.Models.Generated.PlatformPhotoFormat", "GenerationPlatformPhotoPlatformPhotoFormat")
                        .WithMany("GenerationPlatformPhotos")
                        .HasForeignKey("GenerationPlatformPhotoPlatformPhotoFormatId")
                        .HasConstraintName("FK__generatio__gener__6477ECF3");

                    b.Navigation("GenerationPlatformPhotoGenerationPlatform");

                    b.Navigation("GenerationPlatformPhotoPhoto");

                    b.Navigation("GenerationPlatformPhotoPlatformPhotoFormat");
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatformTone", b =>
                {
                    b.HasOne("Mist.Models.Generated.GenerationPlatform", "GenerationPlatformToneGenerationPlatform")
                        .WithOne("GenerationPlatformTone")
                        .HasForeignKey("Mist.Models.Generated.GenerationPlatformTone", "GenerationPlatformToneGenerationPlatformId")
                        .HasConstraintName("FK__generatio__gener__59FA5E80");

                    b.HasOne("Mist.Models.Generated.Tone", "GenerationPlatformToneTone")
                        .WithMany("GenerationPlatformTones")
                        .HasForeignKey("GenerationPlatformToneToneId")
                        .HasConstraintName("FK__generatio__gener__5AEE82B9");

                    b.Navigation("GenerationPlatformToneGenerationPlatform");

                    b.Navigation("GenerationPlatformToneTone");
                });

            modelBuilder.Entity("Mist.Models.Generated.Music", b =>
                {
                    b.HasOne("Mist.Models.Generated.MusicAuthor", "MusicAuthor")
                        .WithMany("Musics")
                        .HasForeignKey("MusicAuthorId")
                        .HasConstraintName("FK__music__music_aut__440B1D61");

                    b.Navigation("MusicAuthor");
                });

            modelBuilder.Entity("Mist.Models.Generated.Photo", b =>
                {
                    b.HasOne("Mist.Models.Generated.PhotoType", "PhotoType")
                        .WithMany("Photos")
                        .HasForeignKey("PhotoTypeId")
                        .HasConstraintName("FK__photo__photo_typ__47DBAE45");

                    b.Navigation("PhotoType");
                });

            modelBuilder.Entity("Mist.Models.Generated.PlatformPhotoFormat", b =>
                {
                    b.HasOne("Mist.Models.Generated.Platform", "PlatformPhotoFormatPlatform")
                        .WithMany("PlatformPhotoFormats")
                        .HasForeignKey("PlatformPhotoFormatPlatformId")
                        .HasConstraintName("FK__platform___platf__4CA06362");

                    b.HasOne("Mist.Models.Generated.PhotoFormatType", "PlatformPhotoFormatType")
                        .WithMany("PlatformPhotoFormats")
                        .HasForeignKey("PlatformPhotoFormatTypeId")
                        .HasConstraintName("FK__platform___platf__4D94879B");

                    b.Navigation("PlatformPhotoFormatPlatform");

                    b.Navigation("PlatformPhotoFormatType");
                });

            modelBuilder.Entity("Mist.Models.Generated.Generation", b =>
                {
                    b.Navigation("GenerationPlatforms");
                });

            modelBuilder.Entity("Mist.Models.Generated.GenerationPlatform", b =>
                {
                    b.Navigation("GenerationPlatformMusicTrack");

                    b.Navigation("GenerationPlatformPhotos");

                    b.Navigation("GenerationPlatformTone");
                });

            modelBuilder.Entity("Mist.Models.Generated.Music", b =>
                {
                    b.Navigation("GenerationPlatformMusicTracks");
                });

            modelBuilder.Entity("Mist.Models.Generated.MusicAuthor", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("Mist.Models.Generated.Photo", b =>
                {
                    b.Navigation("GenerationPlatformPhotos");
                });

            modelBuilder.Entity("Mist.Models.Generated.PhotoFormatType", b =>
                {
                    b.Navigation("PlatformPhotoFormats");
                });

            modelBuilder.Entity("Mist.Models.Generated.PhotoType", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Mist.Models.Generated.Platform", b =>
                {
                    b.Navigation("GenerationPlatforms");

                    b.Navigation("PlatformPhotoFormats");
                });

            modelBuilder.Entity("Mist.Models.Generated.PlatformPhotoFormat", b =>
                {
                    b.Navigation("GenerationPlatformPhotos");
                });

            modelBuilder.Entity("Mist.Models.Generated.Tone", b =>
                {
                    b.Navigation("GenerationPlatformTones");
                });

            modelBuilder.Entity("Mist.Models.Generated.Video", b =>
                {
                    b.Navigation("Generations");
                });
#pragma warning restore 612, 618
        }
    }
}
